apiVersion: v1
kind: Secret
metadata: 
  namespace: three-tier
  name: mongo-sec
type: Opaque
data:  
  password: RWJGaURMY3pJYlMwbkpWZQo= 
  username: c2h1YmhhbXNzYzEwMAo= 
  URL: bW9uZ29kYitzcnY6Ly9zaHViaGFtc3NjMTAwOkViRmlETGN6SWJTMG5KVmVAcHJvamVjdDAuZ3lzdHc4ci5tb25nb2RiLm5ldC9wcm9qZWN0MAo=