apiVersion: apps/v1
kind: Deployment
metadata: 
  name: api
  namespace: three-tier
  labels: 
    role: api
    env: demo
spec: 
  replicas: 2
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector: 
    matchLabels:
      role: api
  template:
    metadata:
      labels:
        role: api
    spec:
      imagePullSecrets:
      - name: dockerhub-registry-secret
      containers:
      - name: api
        image: shubhamshinde2025/threebackend:v1
        imagePullPolicy: Always
        env:
          - name: MONGO_URL
            valueFrom:
              secretKeyRef:
                name: mongo-sec
                key: URL
          - name: MONGO_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-sec
                key: username
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-sec
                key: password
        ports:
        - containerPort: 5000
        livenessProbe: 
          httpGet:
            path: /ok
            port: 5000
          initialDelaySeconds: 2
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ok
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1