apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: three-tier
  labels:
    role: frontend
    env: demo
spec: 
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels: 
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec: 
      imagePullSecrets:
      - name: dockerhub-registry-secret
      containers:
      - name: frontend
        image: shubhamshinde2025/threefrontend:v2
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: "http://16.170.226.163:5000/api/tasks"
        ports:
        - containerPort: 3000