apiVersion: v1
kind: Service
metadata: 
  name: frontend
  namespace: three-tier
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    nodePort: 31000
  type: NodePort
  selector:
    role: frontend