apiVersion: v1
kind: Secret
metadata: 
  namespace: three-tier
  name: mongo-sec
type: Opaque
data:  
  password: RWJGaURMY3pJYlMwbkpWZQo= 
  username: c2h1YmhhbXNzYzEwMAo= 
  URL: bW9uZ29kYitzcnY6Ly9zaHViaGFtc3NjMTAwOkViRmlETGN6SWJTMG5KVmVAcHJvamVjdDAuZ3lzdHc4ci5tb25nb2RiLm5ldC9wcm9qZWN0MAo=

---

apiVersion: apps/v1
kind: Deployment
metadata: 
  namespace: three-tier
  name: mongodb
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels: 
        app: mongodb
    spec: 
      containers:
      - name: mon
        image: mongo
        ports:
        - containerPort: 27017
        env: 
          - name: MONGO_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-sec
                key: username
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-sec
                key: password
          - name: MONGO_URL
            valueFrom:
              secretKeyRef:
                name: mongo-sec
                key: URL      
        
---

apiVersion: v1
kind: Service
metadata:
  namespace: three-tier
  name: mongodb-svc
spec:
  selector:
    app: mongodb
  ports:
  - name: mongodb-svc
    protocol: TCP
    port: 27017
    targetPort: 27017


---

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: backend
  namespace: three-tier
  labels: 
    app: api
    env: demo
spec: 
  replicas: 1
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector: 
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      imagePullSecrets:
      - name: dockerhub-registry-secret
      containers:
      - name: backend
        image: shubhamshinde2025/threebackend:v6
        imagePullPolicy: Always
        env:
          - name: MONGO_URL
            valueFrom:
              secretKeyRef:
                name: mongo-sec
                key: URL
          - name: MONGO_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-sec
                key: username
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-sec
                key: password
---

apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: three-tier
spec: 
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app: api

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: three-tier
  labels:
    app: frontend
    env: demo
spec: 
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels: 
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec: 
      imagePullSecrets:
      - name: dockerhub-registry-secret
      containers:
      - name: frontend
        image: shubhamshinde2025/threefrontend:v6
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: "http://13.48.70.247:5000/api/tasks"
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata: 
  name: frontend-svc
  namespace: three-tier
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: frontend




